### ISSUE TITLE
Refine UI system in native engine

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#12516]
This bug is a collection for all UI related improvement tasks
## Features:
- [X] Easing out for scroll view: https://github.com/cocos2d/cocos2d-x/pull/12466
- [x] Slider: https://github.com/cocos2d/cocos2d-x/pull/12352
- [x] Slider event handling: https://github.com/cocos2d/cocos2d-x/issues/12351
- [x] Vertical scroll for PageView: https://github.com/cocos2d/cocos2d-x/issues/10778
## Refine:
- [x] Slider precision: https://github.com/cocos2d/cocos2d-x/issues/12350
- [x] Checkbox inside Scrollview: https://github.com/cocos2d/cocos2d-x/issues/11784
- [x] Unify fontSize type for text and label: https://github.com/cocos2d/cocos2d-x/issues/10082
- [x] Memory usage of Text widget: https://github.com/cocos2d/cocos2d-x/issues/9004
## Bugs:
- [x] https://github.com/cocos2d/cocos2d-x/issues/12692
- [x] https://github.com/cocos2d/cocos2d-x/issues/12519
- [x] https://github.com/cocos2d/cocos2d-x/issues/12249
- [x] https://github.com/cocos2d/cocos2d-x/issues/12145
- [x] https://github.com/cocos2d/cocos2d-x/issues/11780
- [x] https://github.com/cocos2d/cocos2d-x/issues/11585
- [x] https://github.com/cocos2d/cocos2d-x/issues/10763
- [x] https://github.com/cocos2d/cocos2d-x/issues/10386
- [x] https://github.com/cocos2d/cocos2d-x/issues/9507
- [x] https://github.com/cocos2d/cocos2d-x/issues/9500
- [x] https://github.com/cocos2d/cocos2d-x/issues/9496
- [x] https://github.com/cocos2d/cocos2d-x/issues/9400
- [x] https://github.com/cocos2d/cocos2d-x/issues/9382

**Comment by man2** [comment]
could you guys add batch draw for TextBMFont(s) and LabelBMFont(s)? for now each BMFont is rendered in 1 draw call. I have my implementation which replace each character with a Sprite. But I think it's not the most clever idea

**Comment by zeyangl** [comment]
seriously need auto batching BMFont here.

**Comment by zilongshanren** [comment]
@zeyangl  Sorry for the late reply.
@WenhaiLin  Could you add BMFont batch support? Is it difficult?

**Comment by zilongshanren** [comment]
@man2  @zeyangl  

Now TextBMFont and TextAtlas batch has been implemented.
Here is the PR:https://github.com/cocos2d/cocos2d-x/pull/13201

**Comment by man2** [comment]
nice!! thanks!! is there some usage difference with the previous one?

**Comment by zilongshanren** [comment]
@man2  No, the batch happens automatically.

**Comment by zeyangl** [comment]
It doesn't seem directly merge-able with 3.7 or 3.6. Is it coming out on 3.8?

**Comment by zilongshanren** [comment]
@zeyangl  Yes, it is only available in v3.8.

**Comment by zeyangl** [comment]
what's the release schedule for v3.8?

**Comment by zilongshanren** [comment]
@zeyangl  next week, there will be a v3.8 beta version release.
