### ISSUE TITLE
PolygonSprite operation invalid.

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#12859]
related pr: https://github.com/cocos2d/cocos2d-x/pull/12841

some APIs must be re-checked:
- [x] setColor: Fix at #12863 
- [x] setOpacity: Fix at #12863
- [x] setTexture: Fix at #12863
- [x] setTextureRect:Fix at #12863
- [x] setPosition: OK
- [x] setAnchorPoint: OK
- [x] setScale: OK
- [x] setFlip: Fix at #13138
- [x] setSkew: OK
- [x] setRotation: OK
- [ ] SpriteBatchNode: Doesn't support, please using auto-batch instead. 
- [x] SpriteFrame: OK

**Comment by fusijie** [comment]
@zilongshanren  please reopen it.
