### ISSUE TITLE
[docs] Documents need to be updated for v4

### ISSUE THREAD

**Issue by PatriceJiang** [cocos2d/cocos2d-x#19878]
- [x] New renderer backend, Metal/GL https://github.com/cocos2d/cocos2d-x/issues/19879
- [x] `C++` & `Lua` API changes https://github.com/cocos2d/cocos2d-x/issues/19880
- [x]  `CMake` relevant build procedure, no more VS/XCode project template https://github.com/cocos2d/cocos2d-x/issues/19881

**Comment by PatriceJiang** [comment]
Changes in v4 (not a full list here).

## New Renderer backend https://github.com/cocos2d/cocos2d-x/issues/19879

support both `Apple Metal` & `OpenGL`
- Device
- Renderer
- ProgramState
- Program
- TriangleCommand
- MeshCommand
- CustomCommand
- Texture2D

-   dynamic/static for Buffer usage
-   shader module and what shader features are not supported


> how it works & how to use?

## API changes https://github.com/cocos2d/cocos2d-x/issues/19880

`C++` & `Lua`

> Changes other than rendering

- new API
- removal API
- rename

## VS&Xcode project template removal https://github.com/cocos2d/cocos2d-x/issues/19881

- How to work with CMake
- How to update Info.plist for MacOSX & iOS projects in CMake project

## README.md

- framework description update
- some contents are removed

## platform specific

### android

- remove `ndk-build` support

### Mac & iOS

- add metal

## removal parts

- remove JS/web/html5 language support
- remove some editor support
- remove SimpleAudioEngine
- remove GLNode
- remove DrawPrimitives
- remove Simulator
- remove old Label
- remove GL codes


## submodules

### 3rd-party-libs-bin

- add `glsl-optimizer`

### console

### binding-generator


## spine

not merged

- using spine-c++ API instead of spine-c API

**Comment by Bilalmirza** [comment]
Please make sure you include spine support. Esoteric still haven't merged the pull request.

**Comment by Bilalmirza** [comment]
Sorry your full list wasn't visible to me when i replied.

**Comment by minggo** [comment]
But we don't know how to make Esoteric merge the PR.

**Comment by minggo** [comment]
> Fix EGL context lost issue

I think it is not needed because v3 also has this feature.

Some contents added:

- dynamic/static for Buffer usage
- what shader features are not supported

**Comment by PatriceJiang** [comment]
okay  @minggo

**Comment by Bilalmirza** [comment]
@minggo I'll ask esoteric in forums to merge the PR
